# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_brand',
                'doc_host': 'https://marcusinthesky.github.io',
                'git_url': 'https://github.com/marcusinthesky/nbdev_brand',
                'lib_path': 'nbdev_brand'},
  'syms': {'nbdev_brand.core': {'nbdev_brand.core.foo': ('core.html#foo', 'nbdev_brand/core.py')}}}
